### ISSUE TITLE
"TypeError: Cannot read property 'ToyKit' of undefined" on meteor 1.2.0.2

### ISSUE THREAD

**Issue by stivaugoin** [msavin/JetSetter#15]
I receive this error when I open my app after updating to 1.2.0.2

```
I20151014-13:18:45.044(-4)? Exception while invoking method 'MeteorToys' TypeError: Cannot read property 'ToyKit' of undefined
I20151014-13:18:45.045(-4)?     at [object Object].Meteor.(anonymous function).MeteorToys (packages/msavin_mongol/server/methods.js:1:1)
I20151014-13:18:45.045(-4)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
I20151014-13:18:45.045(-4)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
I20151014-13:18:45.046(-4)?     at livedata_server.js:708:19
I20151014-13:18:45.046(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151014-13:18:45.046(-4)?     at livedata_server.js:706:40
I20151014-13:18:45.047(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151014-13:18:45.047(-4)?     at livedata_server.js:704:46
I20151014-13:18:45.048(-4)?     at tryCallTwo (/home/stiv/.meteor/packages/promise/.0.5.0.rmmk1z++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151014-13:18:45.048(-4)?     at doResolve (/home/stiv/.meteor/packages/promise/.0.5.0.rmmk1z++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
```

I have reinstall this package without success.

I have msavin:mongol installed too.

Thank you

**Comment by msavin** [comment]
Resolved. Please remove and add the packages again

**Comment by stivaugoin** [comment]
Thanks, it's works!
